version: '3.9'
services:
  web:
    build: .
    ports:
      
"5000:5000"
  environment:
FLASK_ENV=development
volumes:
.:/app
depends_on:
db
db:
  image: mysql:8.0
  restart: always
  environment:
    MYSQL_ROOT_PASSWORD: Agusrodpro1
    MYSQL_DATABASE: SistemaDeBiblioteca
  ports:- "3306:3306"